MvcRehber1/Controllers/KisiController.cs
using MvcRehber1.Models.Context;
using MvcRehber1.Models.Entitites;
using MvcRehber1.Models.KisiModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace rehber.Controllers
{
    public class KisiController : Controller
    {
        MvcRehber1Context db = new MvcRehber1Context();
        // GET: Kisi
        public ActionResult Index()
        {
            var simdikiKullanici = Convert.ToInt32(Session["IdSS"]);

            var model = new KisiIndexViewModel
            {
                Kisiler = db.Kisiler.Where(x=>x.CurrentId == simdikiKullanici).ToList(),
                Sehirler = db.Sehirler.ToList(),
                Kullanicilar = db.Kullanicilar.ToList()
            };
            return View(model);
        }
        [HttpGet]
        public ActionResult Ekle()
        {
            var model = new KisiEkleViewModel
            {
                Kisi = new Kisi(),
                Sehirler = db.Sehirler.ToList(),
                Kullanicilar = db.Kullanicilar.ToList()

            };
            return View(model);

        }
        [HttpPost]
        public ActionResult Ekle(Kisi kisi)
        {
            try
            {
                kisi.CurrentId = Convert.ToInt32(Session["IdSS"]);
                db.Kisiler.Add(kisi);
                db.SaveChanges();

                TempData["BasariliMesaj"] = "Ekleme İşlemi Başarıyla Gerçekleşti.";

            }
            catch (Exception)
            {
                TempData["HataliMesaj"] = "Hata Oluştu! Lütfen Yeniden Deneyiniz.";

            }

            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            var kisi = db.Kisiler.Find(id);

            if (kisi == null)
            {
                TempData["HataliMesaj"] = "Güncellenmek istenen kayıt bulunamadı!";
                return RedirectToAction("Index");

            }
            var model = new KisiGuncelleViewModel
            {
                Kisi = kisi,
                Sehirler = db.Sehirler.ToList(),
                Kullanicilar = db.Kullanicilar.ToList()

            };

            ViewBag.Sehirler = new SelectList(db.Sehirler.ToList(), "Id", "SehirAdi");
            return View(model);

        }
        [HttpPost]
        public ActionResult Guncelle(Kisi kisi)
        {
            var eskiKisi = db.Kisiler.Find(kisi.Id);

            if (eskiKisi == null)
            {
                TempData["HataliMesaj"] = "Güncellenmek istenen kayıt bulunamadı!";
                return RedirectToAction("Index");

            }
            eskiKisi.Ad = kisi.Ad;
            eskiKisi.Soyad = kisi.Soyad;
            eskiKisi.CepTelefon = kisi.CepTelefon;
            eskiKisi.Email = kisi.Email;
            eskiKisi.Adres = kisi.Adres;
            eskiKisi.SehirId = kisi.SehirId;

            db.SaveChanges();

            TempData["BasariliMesaj"] = "Kişi Bilgeleri Başarıyla Güncellendi.";


            return RedirectToAction("Index");

        }

        [HttpGet]

        public ActionResult Detay(int id)
        {

            var kisi = db.Kisiler.Find(id);

            if (kisi == null)
            {
                TempData["HataliMesaj"] = "Kişi Bulunamadı!";
                return RedirectToAction("Index");

            }
            var model = new KisiDetayViewModel
            {
                Kisi = kisi,
                Sehirler = db.Sehirler.ToList()
            };
            return View(model);
        }

        public ActionResult Sil(int id)
        {
            var kisi = db.Kisiler.Find(id);

            if (kisi == null)
            {
                TempData["HataliMesaj"] = "Kişi Bulunamadı!";
                return RedirectToAction("Index");
            }
            db.Kisiler.Remove(kisi);
            db.SaveChanges();

            TempData["BasariliMesaj"] = "Kişi Veritabanından Silinmiştir";


            return RedirectToAction("Index");
        }


    }
}

MvcRehber1/Controllers/SehirController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcRehber1.Models.Context;
using MvcRehber1.Models.Entitites;

namespace MvcRehber1.Controllers
{
    public class SehirController : Controller
    {
        private MvcRehber1Context db = new MvcRehber1Context();

        // GET: Sehir
        public ActionResult Index()
        {
            return View(db.Sehirler.ToList());
        }

        // GET: Sehir/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sehir sehir = db.Sehirler.Find(id);
            if (sehir == null)
            {
                return HttpNotFound();
            }
            return View(sehir);
        }

        // GET: Sehir/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sehir/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,SehirAdi,PlakaKodu")] Sehir sehir)
        {
            if (ModelState.IsValid)
            {
                db.Sehirler.Add(sehir);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sehir);
        }

        // GET: Sehir/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sehir sehir = db.Sehirler.Find(id);
            if (sehir == null)
            {
                return HttpNotFound();
            }
            return View(sehir);
        }

        // POST: Sehir/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,SehirAdi,PlakaKodu")] Sehir sehir)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sehir).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sehir);
        }

        // GET: Sehir/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sehir sehir = db.Sehirler.Find(id);
            if (sehir == null)
            {
                return HttpNotFound();
            }
            return View(sehir);
        }

        // POST: Sehir/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sehir sehir = db.Sehirler.Find(id);
            db.Sehirler.Remove(sehir);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MvcRehber1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>


<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                @if (Session["UsernameSS"] != null)
                {
                    @Html.ActionLink("Rehber", "Index", "Kisi", new { area = "" }, new { @class = "navbar-brand" })
                }

            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (Session["UsernameSS"] != null)
                    {

                        <li>@Html.ActionLink("Şehirler", "Index", "Sehir")</li>
                        <li>@Html.ActionLink("Kişiler", "Index", "Kisi")</li>

                    }

                </ul>
                <ul class="nav navbar-nav" style="float:right !important">
                    @if (Session["UsernameSS"] != null)
                    {
                        <li> <p style="color:brown;margin-top:15px;"> Hello @Session["UsernameSS"]!</p></li>
                        <li>@Html.ActionLink("Çıkış Yap", "CikisYap", "Kullanici")</li>

                    }
                    else
                    {
                        <li>@Html.ActionLink("Kayıt Ol", "Kaydol", "Kullanici")</li>
                        <li>@Html.ActionLink("Giriş Yap", "GirisYap", "Kullanici")</li>
                    }

                </ul>

            </div>

        </div>
    </div>
    <div class="container body-content">
        @if (TempData["BasariliMesaj"] != null)
        {

            <div class="alert alert-success">
                @TempData["BasariliMesaj"]
            </div>

        }

        @if (TempData["HatlaliMesaj"] != null)
        {
            <div class="alert alert-danger">
                @TempData["HataliMesaj"];
            </div>
        }




        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Bize Ulaşın: 0555 555 55 55</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>